### ISSUE TITLE
AI King Piece Movement Issue

### ISSUE THREAD

**Issue by blairck** [blairck/claudius#27]
The AI has an issue moving one of its king pieces. Perhaps it cannot move backwards? In this example, the AI has only king pieces and generates a IndexError when trying to make its move.
```
  1  2  3  4  5  6  7  8  9  0
0    A     .     .     .     . 0
9 .     .     .     .     .    9
8    .     .     .     A     . 8
7 .     .     .     .     .    7
6    .     .     .     b     . 6
5 .     .     .     .     .    5
4    .     .     .     .     . 4
3 .     b     .     .     .    3
2    .     .     .     .     . 2
1 .     b     .     .     .    1
  1  2  3  4  5  6  7  8  9  0
Enter a move: 3342
  1  2  3  4  5  6  7  8  9  0
0    A     .     .     .     . 0
9 .     .     .     .     .    9
8    .     .     .     A     . 8
7 .     .     .     .     .    7
6    .     .     .     b     . 6
5 .     .     .     .     .    5
4    .     .     .     .     . 4
3 .     .     .     .     .    3
2    .     b     .     .     . 2
1 .     b     .     .     .    1
  1  2  3  4  5  6  7  8  9  0
--------------------------------
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    game = ai.randomSearch(game, COMP_IS_PLAYER_A)
  File "/Users/blair/Documents/workshop/claudius/src/ai.py", line 15, in randomSearch
    return moves[0]
IndexError: list index out of range
Christophers-MacBook-Pro:claudius ckblair$ 
```

**Comment by blairck** [comment]
```
Using custom starting position...
  1  2  3  4  5  6  7  8  9  0
0    A     .     .     .     . 0
9 .     .     .     .     .    9
8    .     .     .     A     . 8
7 .     .     .     .     .    7
6    .     .     .     b     . 6
5 .     .     .     .     .    5
4    .     .     .     .     . 4
3 .     .     .     .     .    3
2    .     b     .     .     . 2
1 .     b     .     .     .    1
  1  2  3  4  5  6  7  8  9  0
--------------------------------
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    game = ai.randomSearch(game, COMP_IS_PLAYER_A)
  File "/Users/blair/Documents/workshop/claudius/src/ai.py", line 15, in randomSearch
    return moves[0]
IndexError: list index out of range
```
I was able to recreate this bug. There is an issue with ai.getNoncaptureMovesForRegularPiece() which only generates forward-direction moves for regular pieces, and not king pieces. This logic should perhaps live in rules.legalMoveP(), except king logic isn't there either. Also, legalMoveP() isn't actually used anywhere in the code? There needs to be some fixing/refactoring/consolidating done here.
